name: Destroy OpenFaaS Function

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install faas-cli
      run: curl -sSL https://cli.openfaas.com | sudo sh

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Login to OpenFaaS
      run: echo "${{ secrets.OPENFAAS_PASSWORD }}" | faas-cli login --username admin --password-stdin --gateway ${{ secrets.OPENFAAS_URL }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      env:
        OPENFAAS_URL: ${{ secrets.OPENFAAS_URL }}
      run: terraform destroy -auto-approve